// ui-vue/src/components/TaskList.vue
<template>
    <div>
        <p>Open</p>
        <ul>
            <task-list-element v-for="task in openTasks" :key="task.name" v-bind:task="task"></task-list-element>
        </ul>

        <p>Closed</p>
        <ul>
            <task-list-element v-for="task in closedTasks" :key="task.name" v-bind:task="task"></task-list-element>
        </ul>
    </div>
</template>
<script>
    import TaskListElement from './TaskListElement.vue'

    export default {
        name: 'TaskList',
        components: {
            TaskListElement
        },
        computed: {
            openTasks: function () {
                return this.$store.state.tasks.filter(_ => _.closed === false)
            },
            closedTasks: function () {
                return this.$store.state.tasks.filter(_ => _.closed === true)
            }
        }
    }
</script>

// ui-react/src/js/components/TaskList.js
import React from "react";
import TaskListElement from "./TaskListElement";
import {connect} from "react-redux";

const mapStateToProps = state => {
    return {
        openTasks: state.tasks.filter(_ => _.closed === false),
        closedTasks: state.tasks.filter(_ => _.closed === true)
    };
};

class TaskListComponent extends React.Component {
    render() {
        return (
            <div>
                <p>Open</p>
                <ul>
                    {
                        this.props.openTasks.map(task => {
                            return <TaskListElement key={task.name} task={task}/>
                        })
                    }
                </ul>

                <p>Closed</p>
                <ul>
                    {
                        this.props.closedTasks.map(task => {
                            return <TaskListElement key={task.name} task={task}/>
                        })
                    }
                </ul>
            </div>
        )
    }
}

const TaskList = connect(mapStateToProps)(TaskListComponent);

export default TaskList;
