// ui-vue/src/components/TaskList.vue
<template>
    <div>
        <p>Open</p>
        <ul>
            <task-list-element v-for="task in openTasks" :key="task.name" v-bind:task="task"></task-list-element>
        </ul>

        <p>Closed</p>
        <ul>
            <task-list-element v-for="task in closedTasks" :key="task.name" v-bind:task="task"></task-list-element>
        </ul>
    </div>
</template>
<script>
    import TaskListElement from './TaskListElement.vue'

    export default {
        name: 'TaskList',
        components: {
            TaskListElement
        },
        computed: {
            openTasks: function () {
                return this.$store.state.tasks.filter(_ => _.closed === false)
            },
            closedTasks: function () {
                return this.$store.state.tasks.filter(_ => _.closed === true)
            }
        }
    }
</script>

// ui-angular/src/app/task-list/task-list.component.ts
import {Component} from "@angular/core";
import {Observable} from "rxjs/index";
import {Task} from "../model/task.model";
import {StateService} from "../model/state.service";
import {map} from "rxjs/internal/operators";


@Component({
    selector: 'app-task-list',
    templateUrl: './task-list.component.html',
    styleUrls: ['./task-list.component.css']
})
export class TaskListComponent {

    private readonly tasks: Observable<Task[]> = this.stateService.tasks;

    public readonly openTasks: Observable<Task[]> = this.tasks
        .pipe(map((tasks: Task[]) => tasks.filter(task => task.closed === false)));

    public readonly closedTasks: Observable<Task[]> = this.tasks
        .pipe(map((tasks: Task[]) => tasks.filter(task => task.closed === true)));

    constructor(private stateService: StateService) {
    }
}

<div>
    <h2>Open</h2>
    <mat-list>
        <app-task-list-element *ngFor="let task of openTasks | async" [task]="task"></app-task-list-element>
    </mat-list>

    <h2>Closed</h2>
    <mat-list>
        <app-task-list-element *ngFor="let task of closedTasks | async" [task]="task"></app-task-list-element>
    </mat-list>
</div>
